language: python
python:
  - "3.3"
# command to install dependencies
install:
  - pip install nose
  - pip install coverage
# command to run tests
script: 
  - nosetests
  - coverage run --branch mailmerge_test.py && coverage report
